### PR TITLE
Add `add`, `delete`, `list`, `find`, `clear` project commands

### LINKED ISSUE #48: Add `add`, `delete`, `list`, `find`, `clear` project commands

### PR DESCRIPTION
**Pull request by LeeZeHao**
Fixes #48

### CODE REVIEW

**Comment by LeeZeHao** [comment]
`addproject` and `deleteproject` commands added

**Comment by LeeZeHao** [comment]
`findproject` and `listproject` commands added

**Comment by LeeZeHao** [comment]
`clearproject` command added

Behavior:
`clear` command only clears persons
`clearproject` command only clears projects

**Review by SamuelFoo — APPROVED** [review]
LGTM!

Try to split into different pull requests. In this case there could be one PR per command so that we don't have to deal with so many merge conflicts.

One nit is that some of your commit message headers are too long (over 50 characters). If you are using VSCode, you can set `git.inputValidationSubjectLength` to 50 in 
your `settings.json`. This will alert you whenever your commit messages are too long.

**Pull request merged**
